
#' Classical Over Representation Analysis with FOBI
#'
#' @description This function performs a traditional Over Representation Analysis by hypergeometric test: classes are treated as sets of individual metabolites and all metabolites are treated as equally informative. This function uses Food-Biomarker Ontology knowledge as biological information.
#'
#' @param metaboliteList A vector of FOBI metabolite identifiers that define the selected list of metabolites. Other accepted identifiers are: HMDB, KEGG, PubChemCID, InChIKey, InChICode, and ChemSpider.
#' @param metaboliteUniverse A vector of FOBI metabolite identifiers that define the universe of possible metabolites. The identifiers should be of the same type as the `metaboliteList` identifiers.
#' @param subOntology A string specifying one of the two FOBI sub-ontologies: "food", or "biomarker".
#' @param pvalCutoff A numeric value indicating a p-value cutoff for p-values generated by the hypergeometric test.
#' @param adjust A string indicating a multiple testing method to use. Options are: "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", and "fdr".
#' @param fobi FOBI table obtained with `parse_fobi()`. If this value is set to NULL, the last version of FOBI will be downloaded from GitHub.
#'
#' @export
#'
#' @return A tibble with ORA results.
#' @references Foroushani AB, Brinkman FS and Lynn DJ (2013). Pathway-GPS and SIGORA:identifying relevant pathways based on the over-representation of their gene-pair signatures. PeerJ, 1, pp. e229.
#' @references Pol Castellano-Escuder, Raúl González-Domínguez, David S Wishart, Cristina Andrés-Lacueva, Alex Sánchez-Pla, FOBI: an ontology to represent food intake data and associate it with metabolomic data, Database, Volume 2020, 2020, baaa033, https://doi.org/10.1093/databa/baaa033.
#' @author Pol Castellano-Escuder
#'
#' @examples
#' 
#' metaboliteUniverse <- c(fobitools::idmap$FOBI[1:200], fobitools::idmap$FOBI[400:450])
#' metaboliteList <- c(fobitools::idmap$FOBI[1:50], fobitools::idmap$FOBI[70:80])
#' 
#' # Food enrichment analysis
#' fobitools::ora(metaboliteList = metaboliteList, 
#'                metaboliteUniverse = metaboliteUniverse, 
#'                pvalCutoff = 1)
#' 
#' # Chemical class enrichment analysis
#' fobitools::ora(metaboliteList = metaboliteList, 
#'                metaboliteUniverse = metaboliteUniverse, 
#'                subOntology = "biomarker", 
#'                pvalCutoff = 1, adjust = "fdr")
#' 
#' @importFrom magrittr %>%
#' @importFrom tidyr unnest
#' @importFrom dplyr mutate select rename filter mutate_all rowwise pull arrange desc as_tibble mutate_at
#' @importFrom stringr regex str_replace_all str_trim
#' @importFrom sigora makeGPS
ora <- function(metaboliteList,
                metaboliteUniverse,
                subOntology = "food",
                pvalCutoff = 0.01,
                # adjust = "fdr",
                fobi = fobitools::fobi){

  if (is.null(metaboliteList)) {
    stop("metaboliteList must be a vector with selected metabolites")
  }
  if (!is.vector(metaboliteList)) {
    stop("metaboliteList must be a vector with selected metabolites")
  }
  if (is.null(metaboliteUniverse)) {
    stop("metaboliteUniverse must be a vector with the universe of possible metabolites")
  }
  if (!is.vector(metaboliteUniverse)) {
    stop("metaboliteUniverse must be a vector with the universe of possible metabolites")
  }
  if (!(subOntology %in% c("food", "biomarker"))) {
    stop("Incorrect value for subOntology argument. Options are 'food' and 'biomarker'")
  }
  if (pvalCutoff < 0) {
    stop("pvalCutoff cannot be less than zero")
  }
  # if (!(adjust %in% c("holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr"))) {
  #   stop("Incorrect value for adjust argument")
  # }

  ##

  if (is.null(fobi)){
    fobi <- parse_fobi()
  }
  
  ##
  
  # idmap <- fobi %>%
  #   filter(!BiomarkerOf == "NULL") %>%
  #   select(name, FOBI, HMDB, KEGG, PubChemCID, InChIKey, InChICode, ChemSpider) %>%
  #   mutate_all(as.character) %>%
  #   mutate_at(c("HMDB", "KEGG", "PubChemCID", "ChemSpider"), ~ str_replace_all(., regex("( ).*"), regex("\\1"))) %>%
  #   rename(metaboliteNames = name) %>%
  #   mutate_all(~ ifelse(. == "NULL", NA, .)) %>%
  #   mutate_all(~ stringr::str_trim(.)) %>%
  #   filter(!duplicated(metaboliteNames))
  
  n_metaboliteUniverse <- length(unique(metaboliteUniverse[!is.na(metaboliteUniverse)]))
  metaboliteUniverse <- unique(metaboliteUniverse[!is.na(metaboliteUniverse)])
  
  # universe_names <- fobitools::idmap %>%
  #   # rowwise() %>% 
  #   filter(FOBI %in% unique(metaboliteUniverse[!is.na(metaboliteUniverse)])) %>%
  #   pull(FOBI)
    
  ##

  ptw_foods <- fobi %>%
    filter(!BiomarkerOf == "NULL") %>%
    select(id_BiomarkerOf, BiomarkerOf, name, FOBI) %>%
    tidyr::unnest(cols = c(id_BiomarkerOf, BiomarkerOf, name, FOBI)) %>%
    # filter(FOBI %in% universe_names) %>%
    mutate_all(as.factor)

  ##
  
  ptw_chemicals <- fobi %>%
    filter(!BiomarkerOf == "NULL") %>%
    select(is_a_code, is_a_name, name, FOBI) %>%
    tidyr::unnest(cols = c(is_a_code, is_a_name, name, FOBI)) %>%
    # filter(name %in% universe_names) %>%
    mutate_all(as.factor) %>%
    filter(!duplicated(.))

  ##

  n_food_metabolites <- ptw_foods %>%
    filter(FOBI %in% metaboliteUniverse) %>%
    filter(duplicated(id_BiomarkerOf))
  
  n_biomarker_metabolites <- ptw_chemicals %>%
    filter(FOBI %in% metaboliteUniverse) %>%
    filter(duplicated(is_a_code)) 

  ##
  
  if (subOntology == "food") {
    if(nrow(n_food_metabolites) > 1){
      ptw <- unstack(ptw_foods[, c(4,2)])
    }
    else {
      stop("At least two FOBI food classes must be represented by more than one compound in the metaboliteUniverse!")
    }
  }
  
  else if (subOntology == "biomarker") {
    if(nrow(n_biomarker_metabolites) > 1){
      ptw <- unstack(ptw_chemicals[, c(4,2)])
    }
    else {
      stop("At least two FOBI chemical classes must be represented by more than one compound in the metaboliteUniverse!")
    }
  }
  
  ##

  metaboliteList <- unique(metaboliteList[!is.na(metaboliteList)])
  n_metaboliteList <- length(metaboliteList)
  
  ## ORA
  
  res_ora <- fgsea::fora(pathways = ptw, genes = metaboliteList, universe = metaboliteUniverse, minSize = 1, maxSize = Inf)
  
  result <- res_ora %>%
    rename(className = pathway, classSize = size, overlapMetabolites = overlapGenes) %>%
    dplyr::select(className, classSize, overlap, pval, padj, overlapMetabolites) %>%
    arrange(-desc(pval)) %>%
    filter(pval <= pvalCutoff) %>%
    as_tibble()

  message(paste0(crayon::blue("metaboliteUniverse size: ", n_metaboliteUniverse), 
                 "\n",
                 crayon::blue("metaboliteList size: ", n_metaboliteList)))
  
  return(result)
  
}

